services:
  portfolio:
    image: nginx:alpine
    container_name: portfolio_app
    ports:
      - "8084:80"
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    networks:
      - routing_net

networks:
  routing_net:
    driver: bridge
    external: true
